# Dependencies
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'


# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            MP
tagline:          'Data'
description:      'whatever'
url:              https://github.com/martinapre
baseurl:          /

paginate:         5

author:
  name:           'MP'
  url:            https://github.com/martinapre
    
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/martinapre
