# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            MP
tagline:          'Data'
description:      'whatever'
url:              https://github.com/martinapre
baseurl:          /

paginate:         5

author:
  name:           'MP'
  url:            https://github.com/martinapre


github:
  repo:           https://github.com/martinapre
